# Project Information
site_name: PagerDuty Postincident Reviews Howie
site_description: A guide to the postincident review process, outlining how to collect data, hold meetings, and publish learnings. Originally by the folks at Jeli.
site_author: PagerDuty, Inc.
site_url: https://howie-guide.pagerduty.com/

# Repository
repo_url: https://github.com/pagerduty/postincident-howie-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme:
  name: pagerduty
  title: 'Postincident Howie'

# Contents
nav:
  - Home: 'index.md'
  - Assign: 'assign.md'
  - Identify: 'identify.md'
  - Analyze: 'analyze.md'
  - Interview: 'interview.md'
  - Calibrate: 'calibrate.md'
  - Meet: 'meet.md'
  - Report: 'report.md'
  - Distribute: 'distribute.md'
  - Closing Thoughts: 'thoughts.md'
  - Continued Learning: 'continue.md'
  - Appendices: 'appendices.md'
  - Authors & Acknowledgements: 'authack.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.tabbed:

# Development URL, bind to local only.
dev_addr: '127.0.0.1:8000'

extra_css:
- authors.css